name: CI CSharp

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths: './CSharpCore'

defaults:
  run:
    working-directory: ./CSharpCore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
